spring:
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    consumer:
      group-id: app.2
    bootstrap-servers: localhost:9092
  application:
    name: analytic-service
  datasource:
    name: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/messenger
server:
  port: 8903
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: analytic-service
