spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: jarymorfifa@gmail.com
    password: cqrz mszt utzw srzd
    port: 587
  kafka:
    consumer:
      group-id: app.1
    bootstrap-servers: localhost:9092
  application:
    name: notification-service
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

