spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: true
server:
  port: 8904
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /api-docs
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
  level:
    org.springframework.security: DEBUG

token:
  secret:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration_days: 7


